"""Typer commands entering the invoices feature module."""

import asyncio
from typing import Annotated

import typer

from shop.application.invoices.get_invoice import GetInvoiceRequest
from shop.cli.context import get_context

invoices = typer.Typer(
    help="Retrieve invoices generated by the background consumer.",
    no_args_is_help=True,
    rich_markup_mode="rich",
)


@invoices.command("get")
def get_invoice(
    context: typer.Context,
    order: Annotated[int, typer.Option("--order", min=1, help="Order identifier.")],
) -> None:
    """Retrieve the invoice generated for one order."""
    cli = get_context(context)
    result = asyncio.run(cli.send(GetInvoiceRequest(order)))
    cli.success(
        "Invoice found",
        {
            "Invoice": f"#{result.invoice_id}",
            "Order": f"#{result.order_id}",
            "Customer": f"#{result.customer_id}",
            "Total": f"£{result.total_pence / 100:.2f}",
            "Document": result.document_url,
        },
    )
