"""Compact, branded invoice and statement PDFs."""

import asyncio
from datetime import date
from html import escape

from shop.ports.invoices.create_invoice import CreateInvoiceRenderer
from shop.ports.statements.create_monthly_statement import MonthlyStatementRenderer
from weasyprint import HTML

_PDF_LIMIT = 4_000_000


class WeasyPrintDocumentRenderer(CreateInvoiceRenderer, MonthlyStatementRenderer):
    """Render the shop's customer documents as compact branded PDFs."""

    async def render_invoice(self, order_id: int, customer_id: int, total_pence: int) -> bytes:
        body = f"""
        <p class="eyebrow">Invoice</p>
        <h1>Thanks for your order.</h1>
        <p class="lede">A clear record of your purchase from Shop.</p>
        <section class="metrics">
          <div><span>Invoice for</span><strong>Order #{order_id}</strong></div>
          <div><span>Customer</span><strong>#{customer_id}</strong></div>
          <div class="accent"><span>Total</span><strong>£{total_pence / 100:,.2f}</strong></div>
        </section>
        <p class="note">Payment received · Keep this document for your records.</p>
        """
        return await self._render("Shop invoice", body)

    async def render_statement(
        self,
        customer_id: int,
        year: int,
        month: int,
        currency: str,
        order_count: int,
        total_minor: int,
    ) -> bytes:
        period = date(year, month, 1).strftime("%B %Y")
        currency_code = escape(currency.upper())
        body = f"""
        <p class="eyebrow">Monthly statement</p>
        <h1>{escape(period)}, at a glance.</h1>
        <p class="lede">Your Shop activity, neatly wrapped up.</p>
        <section class="metrics">
          <div><span>Customer</span><strong>#{customer_id}</strong></div>
          <div><span>Completed orders</span><strong>{order_count}</strong></div>
          <div class="accent"><span>Net spend</span>
            <strong>{currency_code} {total_minor / 100:,.2f}</strong>
          </div>
        </section>
        <p class="note">Totals exclude cancelled orders and include processed refunds.</p>
        """
        return await self._render(f"Shop statement · {period}", body)

    async def _render(self, title: str, body: str) -> bytes:
        pdf = await asyncio.to_thread(_render_pdf, title, body)
        if len(pdf) >= _PDF_LIMIT:
            raise ValueError("rendered document exceeds the 4 MB limit")
        return pdf


def _render_pdf(title: str, body: str) -> bytes:
    html = f"""<!doctype html>
    <html lang="en"><head><meta charset="utf-8"><title>{escape(title)}</title>
    <style>
      @page {{
        background: white; size: A4; margin: 18mm;
        @bottom-right {{ content: "SHOP · " counter(page); color: #667085; font-size: 8pt; }}
      }}
      * {{ box-sizing: border-box; }}
      body {{
        background: white; color: #17223b; font-family: Arial, sans-serif;
        font-size: 10pt; margin: 0;
      }}
      header {{
        align-items: center; border-bottom: 1px solid #dbe4ff; display: flex;
        justify-content: space-between; padding-bottom: 8mm;
      }}
      .brand {{ color: #2f5bea; font-size: 22pt; font-weight: 800; letter-spacing: -.06em; }}
      .mark {{
        background: #ffcf4a; border-radius: 50%; display: inline-block;
        height: 9px; margin-left: 2px; width: 9px;
      }}
      .meta {{ color: #667085; font-size: 8pt; text-align: right; }}
      main {{ padding-top: 18mm; }}
      .eyebrow {{
        color: #2f5bea; font-size: 8pt; font-weight: 700; letter-spacing: .16em;
        margin: 0 0 4mm; text-transform: uppercase;
      }}
      h1 {{
        font-size: 27pt; letter-spacing: -.04em; line-height: 1.05;
        margin: 0; max-width: 135mm;
      }}
      .lede {{ color: #667085; font-size: 12pt; margin: 5mm 0 14mm; }}
      .metrics {{ display: flex; gap: 4mm; }}
      .metrics div {{
        background: #f5f7ff; border-radius: 4mm; flex: 1; min-height: 34mm; padding: 7mm;
      }}
      .metrics .accent {{ background: #2f5bea; color: white; }}
      .metrics span {{
        display: block; font-size: 8pt; margin-bottom: 5mm;
        opacity: .72; text-transform: uppercase;
      }}
      .metrics strong {{ display: block; font-size: 15pt; line-height: 1.1; }}
      .note {{
        border-left: 3px solid #ffcf4a; color: #475467;
        margin-top: 13mm; padding: 2mm 0 2mm 5mm;
      }}
      footer {{ color: #98a2b3; font-size: 8pt; margin-top: 55mm; }}
    </style></head><body>
      <header><div class="brand">shop<span class="mark"></span></div>
        <div class="meta">Shop documents.<br>Generated locally.</div>
      </header>
      <main>{body}</main><footer>Generated by Shop · shop.example</footer>
    </body></html>"""
    result = HTML(string=html).write_pdf()
    if not isinstance(result, bytes):
        raise TypeError("WeasyPrint did not return PDF bytes")
    return result
