"""Tests for the CQRS example: separate stores, separate shapes, one mediator.

Each test proves a different piece of the split: commands return the minimum, queries
return the denormalized view, the two stores hold genuinely different shapes, the read
model only ever changes because a command handler published an event, and the analytical
query rolls the whole catalog up by tier. Everything runs on a handful of rows — the volume
comparison lives in ``benchmark.py``, not here.
"""

from dataclasses import fields

import pytest
from pymediate.sync import Mediator

from catalog.app import build_mediator
from catalog.domain import (
    AdjustStock,
    CreateProduct,
    GetInventoryReport,
    GetProduct,
    Product,
    ProductNotFoundError,
    ProductView,
    ReadStore,
    SearchProducts,
    WriteStore,
)


@pytest.fixture
def write_store() -> WriteStore:
    return WriteStore()


@pytest.fixture
def read_store() -> ReadStore:
    return ReadStore()


@pytest.fixture
def mediator(write_store: WriteStore, read_store: ReadStore) -> Mediator:
    return build_mediator(write_store=write_store, read_store=read_store)


def test_command_response_is_minimal(mediator: Mediator) -> None:
    created = mediator.send(CreateProduct(name="Keyboard", price=49.99, stock=10))

    assert created.product_id == 1  # generated by SQLite on insert
    assert not hasattr(created, "in_stock")  # a command response, not a read-model view


def test_query_returns_the_denormalized_view(mediator: Mediator) -> None:
    created = mediator.send(CreateProduct(name="Keyboard", price=49.99, stock=10))

    view = mediator.send(GetProduct(product_id=created.product_id))

    assert view.name == "Keyboard"
    assert view.in_stock is True  # derived; the write-side Product has no such field
    assert view.price_tier == "standard"  # 49.99 falls in [20, 100)


def test_the_two_stores_hold_different_shapes() -> None:
    # The write side stores only what a write needs; the read side adds derived columns.
    # A query handler reaching into WriteStore, or a command handler into ReadStore, would
    # be a wiring bug — the split starts with the records themselves being different shapes.
    write_fields = {f.name for f in fields(Product)}
    read_fields = {f.name for f in fields(ProductView)}

    assert write_fields == {"product_id", "name", "price", "stock"}
    assert read_fields - write_fields == {"in_stock", "price_tier"}


def test_read_model_updates_via_the_event_after_a_stock_adjustment(
    mediator: Mediator, read_store: ReadStore
) -> None:
    created = mediator.send(CreateProduct(name="Widget", price=9.99, stock=5))
    reads_before = read_store.reads

    mediator.send(AdjustStock(product_id=created.product_id, delta=-5))
    view = mediator.send(GetProduct(product_id=created.product_id))

    # Nothing called ReadStore.upsert directly from the test — only the command handler's
    # publish, delivered to StockAdjustedProjector, could have produced this.
    assert view.stock == 0
    assert view.in_stock is False
    assert read_store.reads == reads_before + 1  # only the GetProduct query counted as a read


def test_search_filters_to_in_stock_only(mediator: Mediator) -> None:
    keyboard = mediator.send(CreateProduct(name="Keyboard", price=49.99, stock=10))
    out_of_stock = mediator.send(CreateProduct(name="Discontinued Mouse", price=5, stock=0))

    results = mediator.send(SearchProducts(in_stock_only=True))

    ids = {p.product_id for p in results}
    assert keyboard.product_id in ids
    assert out_of_stock.product_id not in ids


def test_get_missing_product_raises(mediator: Mediator) -> None:
    with pytest.raises(ProductNotFoundError):
        mediator.send(GetProduct(product_id=999))


def test_price_tiers(mediator: Mediator) -> None:
    budget = mediator.send(CreateProduct(name="Cable", price=5, stock=1))
    standard = mediator.send(CreateProduct(name="Mouse", price=25, stock=1))
    premium = mediator.send(CreateProduct(name="Monitor", price=250, stock=1))

    budget_view = mediator.send(GetProduct(product_id=budget.product_id))
    standard_view = mediator.send(GetProduct(product_id=standard.product_id))
    premium_view = mediator.send(GetProduct(product_id=premium.product_id))

    assert budget_view.price_tier == "budget"
    assert standard_view.price_tier == "standard"
    assert premium_view.price_tier == "premium"


def test_inventory_report_aggregates_by_tier(mediator: Mediator) -> None:
    # Two standard-tier products and one budget; the rollup groups and sums across them.
    mediator.send(CreateProduct(name="Keyboard", price=40.0, stock=2))  # standard
    mediator.send(CreateProduct(name="Mouse", price=60.0, stock=3))  # standard
    mediator.send(CreateProduct(name="Cable", price=10.0, stock=5))  # budget

    report = mediator.send(GetInventoryReport())
    by_tier = {row.price_tier: row for row in report}

    assert by_tier.keys() == {"budget", "standard"}
    assert by_tier["standard"].product_count == 2
    assert by_tier["standard"].inventory_value == pytest.approx(40.0 * 2 + 60.0 * 3)
    assert by_tier["standard"].avg_price == pytest.approx(50.0)
    assert by_tier["budget"].inventory_value == pytest.approx(10.0 * 5)
