**

!pyproject.toml
!README.md
!LICENSE
!src/
!src/**

!examples/
!examples/100-hexagonal-architecture/
!examples/100-hexagonal-architecture/pyproject.toml
!examples/100-hexagonal-architecture/uv.lock
!examples/100-hexagonal-architecture/packages/
!examples/100-hexagonal-architecture/packages/**
!examples/100-hexagonal-architecture/configuration/
!examples/100-hexagonal-architecture/configuration/*.yaml
