"""PostgreSQL schema owned by the persistence adapter."""

from typing import Any

import psycopg


async def ensure_schema(
    connection: psycopg.AsyncConnection[tuple[Any, ...]],
) -> None:
    """Create the example persistence tables idempotently."""
    async with connection.cursor() as cursor:
        await cursor.execute(
            """CREATE TABLE IF NOT EXISTS statements (
                statement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customer_id BIGINT NOT NULL,
                year INTEGER NOT NULL,
                month INTEGER NOT NULL,
                currency TEXT NOT NULL,
                order_count INTEGER NOT NULL,
                total_minor INTEGER NOT NULL,
                document_url TEXT NOT NULL
            )"""
        )
        await cursor.execute(
            """CREATE TABLE IF NOT EXISTS customers (
                customer_id BIGINT PRIMARY KEY,
                store_credit_pence INTEGER NOT NULL
            )"""
        )
        await cursor.execute(
            """CREATE TABLE IF NOT EXISTS invoices (
                invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_id BIGINT NOT NULL,
                customer_id BIGINT NOT NULL,
                total_pence INTEGER NOT NULL,
                document_url TEXT NOT NULL
            )"""
        )
        await cursor.execute(
            """CREATE UNIQUE INDEX IF NOT EXISTS invoices_order_id_unique
               ON invoices (order_id)"""
        )
        await cursor.execute(
            """CREATE TABLE IF NOT EXISTS orders (
                order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customer_id BIGINT NOT NULL,
                lines_json JSONB NOT NULL,
                total_pence INTEGER NOT NULL,
                placed_on DATE NOT NULL,
                refunded_pence INTEGER NOT NULL,
                status TEXT NOT NULL
            )"""
        )
        await cursor.execute(
            """CREATE TABLE IF NOT EXISTS domain_event_journal (
                sequence BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                event_id UUID NOT NULL UNIQUE,
                event_type TEXT NOT NULL,
                schema_version INTEGER NOT NULL,
                occurred_at TIMESTAMPTZ NOT NULL,
                aggregate_type TEXT NOT NULL,
                aggregate_id TEXT NOT NULL,
                payload_json JSONB NOT NULL
            )"""
        )
        await cursor.execute(
            """CREATE INDEX IF NOT EXISTS domain_event_journal_aggregate
               ON domain_event_journal (aggregate_type, aggregate_id, sequence)"""
        )
        await cursor.execute(
            """CREATE TABLE IF NOT EXISTS outbox_messages (
                message_id UUID PRIMARY KEY,
                event_type TEXT NOT NULL,
                schema_version INTEGER NOT NULL,
                occurred_at TIMESTAMPTZ NOT NULL,
                payload_json JSONB NOT NULL,
                trace_context_json JSONB NOT NULL,
                published_at TIMESTAMPTZ,
                lease_until TIMESTAMPTZ,
                lease_token UUID
            )"""
        )
        await cursor.execute(
            "ALTER TABLE outbox_messages ADD COLUMN IF NOT EXISTS lease_token UUID"
        )
        await cursor.execute(
            """CREATE TABLE IF NOT EXISTS inbox_messages (
                message_id UUID PRIMARY KEY,
                state TEXT NOT NULL,
                lease_until TIMESTAMPTZ,
                lease_token UUID,
                processed_at TIMESTAMPTZ
            )"""
        )
        await cursor.execute("ALTER TABLE inbox_messages ADD COLUMN IF NOT EXISTS lease_token UUID")
