name: Checks

on:
  push:
    branches: [main]
    paths: &code-paths
      - "src/**"
      - "tests/**"
      - "scripts/**"
      - "pyproject.toml"
      - "uv.lock"
      - "tasks.toml"
      - "ruff.toml"
      - "mypy.ini"
      - ".github/workflows/checks.yml"
  pull_request:
    branches: [main]
    paths: *code-paths
  workflow_dispatch:

concurrency:
  group: "checks-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.13"

      - name: Setup uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Sync dependencies
        run: |
          uv sync --only-dev

      - name: Format
        run: |
          uv run poe format:check

      - name: Lint
        run: |
          uv run poe lint --output-format=github

      - name: Type check
        run: |
          uv run poe type
